In [1]:
# Import dataset
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
# load dataset
data = pd.read_csv('heart.csv', delimiter=';', header=0)
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# Pemisahan data atribut dengan label
X = data.drop(columns='target', axis=1)
Y = data['target']

In [4]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [5]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [6]:
#mengecek data jika terjadi kehilangan
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# Mencari berapa banyak nilai target
data["target"].value_counts().sort_values(ascending=True)

target
0    138
1    165
Name: count, dtype: int64

In [8]:
# Fungsi melakukan normalisasi Min-Max
def min_max_normalize(data):
    min_val = np.min(data)
    max_val = np.max(data)
    normalized_data = (data - min_val) / (max_val - min_val)
    return normalized_data

# Contoh data
data = np.array([63, 37, 41, 56, 57, 57, 56, 44, 52, 57])

# Melakukan normalisasi
normalized_data = min_max_normalize(data)

print("Data asli:", data)
print("Data yang dinormalisasi:", normalized_data)

Data asli: [63 37 41 56 57 57 56 44 52 57]
Data yang dinormalisasi: [1.         0.         0.15384615 0.73076923 0.76923077 0.76923077
 0.73076923 0.26923077 0.57692308 0.76923077]

In [9]:
# Pemisahan data training dan testing (split data)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.01,stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (299, 13) (4, 13)

In [10]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (299, 13) (4, 13)

In [11]:
# Pemodelan
model=LogisticRegression()

In [12]:
model.fit(X_train, Y_train)

C:\Users\ARMAN PC\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [13]:
# Model prediksi deteksi penyakit jantung
input_data=(57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction=model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
    print('Pasien Tidak Terkena Penyakit Jantung')
else:
    print('Pasien Terkena Penyakit Jantung')

[1]
Pasien Terkena Penyakit Jantung

C:\Users\ARMAN PC\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [14]:
# Membagi data training dan testing -> 0.1 dan 0,9 data train dan di random sebanyak 2 kali
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y ,test_size=0.1,random_state=2)
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
y_pred=classifier.predict(X_test)

In [15]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
140,51,0,2,120,295,0,0,157,0,0.6,2,0,2
251,43,1,0,132,247,1,0,143,1,0.1,1,4,3
257,50,1,0,144,200,0,0,126,1,0.9,1,0,3
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2
250,51,1,0,140,298,0,1,122,1,4.2,1,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3

In [16]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1
35,46,0,2,142,177,0,0,160,1,1.4,0,0,2
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3
178,43,1,0,120,177,0,0,120,1,2.5,1,0,3
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
192,54,1,0,120,188,0,1,113,0,1.4,1,1,3
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2
232,55,1,0,160,289,0,0,145,1,0.8,1,1,3
157,35,1,1,122,192,0,1,174,0,0.0,2,0,2
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3
235,51,1,0,140,299,0,1,173,1,1.6,2,0,3
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3
159,56,1,1,130,221,0,0,163,0,0.0,2,0,3
209,59,1,0,140,177,0,1,162,1,0.0,2,1,3
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2
142,42,0,2,120,209,0,1,173,0,0.0,1,0,2
169,53,1,0,140,203,1,0,155,1,3.1,0,0,3
217,63,1,0,130,330,1,0,132,1,1.8,2,3,3
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
160,56,1,1,120,240,0,1,169,0,0.0,0,0,2

In [17]:
Y_train, len(Y_train)

(140    1
 251    0
 257    0
 286    0
 250    0
       ..
 75     1
 22     1
 72     1
 15     1
 168    0
 Name: target, Length: 272, dtype: int64,
 272)

In [18]:
Y_test, len(Y_test)

(99     1
 296    0
 89     1
 30     1
 234    0
 292    0
 35     1
 7      1
 178    0
 13     1
 240    0
 65     1
 179    0
 192    0
 147    1
 134    1
 232    0
 157    1
 276    0
 235    0
 112    1
 159    1
 209    0
 197    0
 259    0
 29     1
 142    1
 169    0
 217    0
 3      1
 160    1
 Name: target, dtype: int64,
 31)

In [19]:
# Menghitung nilai akurasi 90:10
print('Accuracy of Naive Bayes Continue classifier on test set: {:.2f}'.format(classifier.score(X_test,Y_test)))
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
hasilpengujian=classification_report(Y_test,y_pred)
print(hasilpengujian)

Accuracy of Naive Bayes Continue classifier on test set: 0.97
[[15  0]
 [ 1 15]]
0.967741935483871
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.94      0.97        16

    accuracy                           0.97        31
   macro avg       0.97      0.97      0.97        31
weighted avg       0.97      0.97      0.97        31

In [20]:
#membagi data training dan testing -> 0.2 dan 0,8 data train dan di random sebanyak 2 kali
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y ,test_size=0.2,random_state=2)
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
y_pred=classifier.predict(X_test)

In [21]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
237,60,1,0,140,293,0,0,170,0,1.2,1,2,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2
77,59,1,1,140,221,0,1,164,1,0.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3

In [22]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3
94,45,0,1,112,160,0,1,138,0,0.0,1,0,2
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3
91,57,1,0,132,207,0,1,168,1,0.0,2,0,3

In [23]:
Y_train, len(Y_train)

(237    0
 106    1
 10     1
 153    1
 77     1
       ..
 75     1
 22     1
 72     1
 15     1
 168    0
 Name: target, Length: 242, dtype: int64,
 242)

In [24]:
Y_test, len(Y_test)

(99     1
 296    0
 89     1
 30     1
 234    0
       ..
 173    0
 94     1
 161    1
 216    0
 91     1
 Name: target, Length: 61, dtype: int64,
 61)

In [25]:
#menghitung nilai akurasi 80:20
print('Accuracy of Naive Bayes Continue classifier on test set: {:.2f}'.format(classifier.score(X_test,Y_test)))
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
hasilpengujian=classification_report(Y_test,y_pred)
print(hasilpengujian)

Accuracy of Naive Bayes Continue classifier on test set: 0.89
[[28  4]
 [ 3 26]]
0.8852459016393442
              precision    recall  f1-score   support

           0       0.90      0.88      0.89        32
           1       0.87      0.90      0.88        29

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61

In [26]:
#membagi data training dan testing -> 0.3 dan 0,7 data train dan di random sebanyak 2 kali
X_train, X_test, Y_train, Y_test = train_test_split(X ,Y ,test_size=0.3,random_state=2)
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
y_pred=classifier.predict(X_test)

In [27]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
281,52,1,0,128,204,1,1,156,1,1.0,1,0,0
226,62,1,1,120,281,0,0,103,0,1.4,1,1,3
109,50,0,0,110,254,0,0,159,0,0.0,2,0,2
64,58,1,2,140,211,1,0,165,0,0.0,2,0,2
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3

In [28]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2
131,49,0,1,134,271,0,1,162,0,0.0,1,0,2
172,58,1,1,120,284,0,0,160,0,1.8,1,0,2
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3

In [29]:
Y_train, len(Y_train)

(281    0
 226    0
 109    1
 64     1
 14     1
       ..
 75     1
 22     1
 72     1
 15     1
 168    0
 Name: target, Length: 212, dtype: int64,
 212)

In [30]:
Y_test, len(Y_test)

(99     1
 296    0
 89     1
 30     1
 234    0
       ..
 20     1
 28     1
 131    1
 172    0
 71     1
 Name: target, Length: 91, dtype: int64,
 91)

In [31]:
#menghitung nilai akurasi 70:30
print('Accuracy of Naive Bayes Continue classifier on test set: {:.2f}'.format(classifier.score(X_test,Y_test)))
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
hasilpengujian=classification_report(Y_test,y_pred)
print(hasilpengujian)

Accuracy of Naive Bayes Continue classifier on test set: 0.86
[[33  8]
 [ 5 45]]
0.8571428571428571
              precision    recall  f1-score   support

           0       0.87      0.80      0.84        41
           1       0.85      0.90      0.87        50

    accuracy                           0.86        91
   macro avg       0.86      0.85      0.85        91
weighted avg       0.86      0.86      0.86        91