In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
irisDataset = pd.read_csv('heart.csv', delimiter=';', header=0)
irisDataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
print(irisDataset['target'].unique())

[1 0]

In [4]:
irisDataset["target"]=pd.factorize(irisDataset.target)[0]
print(irisDataset["target"])

0      0
1      0
2      0
3      0
4      0
      ..
298    1
299    1
300    1
301    1
302    1
Name: target, Length: 303, dtype: int64

In [5]:
irisDataset = irisDataset.drop(labels="sex", axis=1)
print(irisDataset)

     age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0     63   3       145   233    1        0      150      0      2.3      0
1     37   2       130   250    0        1      187      0      3.5      0
2     41   1       130   204    0        0      172      0      1.4      2
3     56   1       120   236    0        1      178      0      0.8      2
4     57   0       120   354    0        1      163      1      0.6      2
..   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...
298   57   0       140   241    0        1      123      1      0.2      1
299   45   3       110   264    0        1      132      0      1.2      1
300   68   0       144   193    1        1      141      0      3.4      1
301   57   0       130   131    0        1      115      1      1.2      1
302   57   1       130   236    0        0      174      0      0.0      1

     ca  thal  target
0     0     1       0
1     0     2       0
2     0     2       0
3     0     2       0
4     0     2       0
..   ..   ...     ...
298   0     3       1
299   0     3       1
300   2     3       1
301   1     3       1
302   1     2       1

[303 rows x 13 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
enc = LabelEncoder()

In [8]:
irisDataset['age']=enc.fit_transform(irisDataset['age'].values)
irisDataset['cp']=enc.fit_transform(irisDataset['cp'].values)
irisDataset['trestbps']=enc.fit_transform(irisDataset['trestbps'].values)
irisDataset['chol']=enc.fit_transform(irisDataset['chol'].values)
irisDataset['fbs']=enc.fit_transform(irisDataset['fbs'].values)
irisDataset['restecg']=enc.fit_transform(irisDataset['restecg'].values)
irisDataset['thalach']=enc.fit_transform(irisDataset['thalach'].values)
irisDataset['exang']=enc.fit_transform(irisDataset['exang'].values)
irisDataset['oldpeak']=enc.fit_transform(irisDataset['oldpeak'].values)
irisDataset['ca']=enc.fit_transform(irisDataset['ca'].values)
irisDataset['thal']=enc.fit_transform(irisDataset['thal'].values)

In [9]:
trs_irisDataset=irisDataset.drop(columns='target')
trs_irisDataset.head()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,29,3,31,64,1,0,49,0,22,0,0,1
1,3,2,22,80,0,1,84,0,32,0,0,2
2,7,1,22,35,0,0,71,0,14,2,0,2
3,22,1,14,67,0,1,76,0,8,2,0,2
4,23,0,14,145,0,1,62,1,6,2,0,2

In [10]:
lbl_irisDataset=irisDataset['target']
lbl_irisDataset.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [11]:
#membagi data training dan testing 0.3 data testing dan di loop sebanyak 2 kali
X_train, X_test, Y_train, Y_test = train_test_split(trs_irisDataset,lbl_irisDataset,test_size=0.2,random_state=2)
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
y_pred=classifier.predict(X_test)

In [12]:
print('Accuracy of Naive Bayes continue classifier on test set: {:.2f}'.format(classifier.score(X_test,Y_test)))
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
hasilpengujian=classification_report(Y_test,y_pred)
print(hasilpengujian)

Accuracy of Naive Bayes continue classifier on test set: 0.89
[[26  3]
 [ 4 28]]
0.8852459016393442
              precision    recall  f1-score   support

           0       0.87      0.90      0.88        29
           1       0.90      0.88      0.89        32

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61

In [13]:
irisDataset = irisDataset.to_numpy()
print(irisDataset)

[[29  3 31 ...  0  1  0]
 [ 3  2 22 ...  0  2  0]
 [ 7  1 22 ...  0  2  0]
 ...
 [34  0 30 ...  2  3  1]
 [23  0 22 ...  1  3  1]
 [23  1 22 ...  1  2  1]]

In [14]:
#data 80 & 20
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)
print(dataTraining)
print()
print(dataTesting)

[[29  3 31 ...  0  1  0]
 [ 3  2 22 ...  0  2  0]
 [ 7  1 22 ...  0  2  0]
 ...
 [12  1  2 ...  0  3  0]
 [20  2  8 ...  0  2  0]
 [24  0  1 ...  0  2  0]]

[[ 17   2  28 127   0   0  41   0  15   2   1   2   0]
 [ 14   1  22  75   0   0  78   0   2   1   0   2   0]
 [ 11   0   4  39   0   0  47   1  28   1   0   2   0]
 [ 19   0  22  93   0   0  42   0   4   1   0   2   0]
 [  5   2  28 134   0   0  80   0   0   2   0   2   0]
 [ 18   1  14 136   0   1  71   0   2   2   0   2   0]
 [ 10   2  28  66   0   0  78   0   0   2   0   2   0]
 [ 13   2  27  86   0   0  55   0   0   2   0   2   0]
 [ 19   2  20  47   0   0  16   0   0   2   0   0   0]
 [ 19   0  27  65   0   0  59   0   0   2   0   2   0]
 [ 14   2  17  84   1   1  74   0   0   2   2   2   0]
 [ 23   0  23  38   0   1  67   1   0   2   0   3   0]
 [ 18   2  27  54   0   1  68   0   0   2   4   2   0]
 [ 20   1  23 112   1   0  58   1   0   2   1   2   0]
 [ 11   1   9   5   0   1  37   0   0   1   0   2   0]
 [ 19   0  29  57   0   0  12   1   0   2   0   3   0]
 [ 28   0  28 147   0   0  56   0  12   1   0   2   0]
 [ 18   0   7  64   1   1  46   0   1   2   3   3   0]
 [  9   2  22 131   0   1  61   0  18   2   1   2   0]
 [ 19   2  22  76   1   0  72   0   0   2   3   2   0]]

In [15]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTraining)
print()
len(labelTraining)

[1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1
 0 0 0 1 0 0]

80

In [16]:
model = GaussianNB()

In [17]:
model = model.fit(inputTraining, labelTraining)

In [18]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya :", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya : [0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1]
Hasil Prediksi : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [19]:
#hasil prediksi 80 & 20
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi benar :", prediksiBenar, "data")
print("Prediksi salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi benar : 16 data
Prediksi salah : 4 data
Akurasi : 80.0 %

In [20]:
#data 20 & 80
dataTraining = np.concatenate((irisDataset[0:10, :], irisDataset[50:60, :]), axis=0)
dataTesting = np.concatenate((irisDataset[10:50, :], irisDataset[60:100, :]), axis=0)
print(dataTraining)
print()

[[ 29   3  31  64   1   0  49   0  22   0   0   1   0]
 [  3   2  22  80   0   1  84   0  32   0   0   2   0]
 [  7   1  22  35   0   0  71   0  14   2   0   2   0]
 [ 22   1  14  67   0   1  76   0   8   2   0   2   0]
 [ 23   0  14 145   0   1  62   1   6   2   0   2   0]
 [ 23   0  28  25   0   1  47   0   4   1   0   1   0]
 [ 22   1  28 116   0   0  52   0  13   1   0   2   0]
 [ 10   1  14  92   0   1  72   0   0   2   0   3   0]
 [ 18   2  43  31   1   1  61   0   5   2   0   3   0]
 [ 23   2  34   9   0   1  73   0  16   2   0   2   0]
 [ 17   2  22  85   0   0  48   0   5   2   0   2   0]
 [ 32   0  14 121   0   0  50   0   4   1   0   2   0]
 [ 28   2  22  62   0   1  45   0  17   1   3   3   0]
 [ 10   2   7   2   0   1  74   0   6   1   0   2   0]
 [ 29   2  25  81   0   0  71   0   0   2   0   2   0]
 [ 18   1  24  33   0   1  57   0   8   2   1   2   0]
 [ 14   0  15  53   0   0  83   0   0   2   0   2   0]
 [ 11   0  11  89   0   0  82   0   0   2   0   2   0]
 [  1   3  13  18   0   0  73   0   0   2   0   2   0]
 [ 23   0  20 122   0   0  58   0   0   2   1   2   0]]

In [21]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTraining)
print()
len(labelTraining)

[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]

20

In [22]:
model = GaussianNB()

In [23]:
model = model.fit(inputTraining, labelTraining)

In [24]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya :", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya : [0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1
 0 0 0 1 0 1]
Hasil Prediksi : [0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]

In [25]:
#prediksi 20 & 80
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi benar :", prediksiBenar, "data")
print("Prediksi salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi benar : 63 data
Prediksi salah : 17 data
Akurasi : 78.75 %

In [26]:
#data 40 & 60
dataTraining = np.concatenate((irisDataset[0:20, :], irisDataset[50:70, :]), axis=0)
dataTesting = np.concatenate((irisDataset[20:50, :], irisDataset[70:100, :]), axis=0)
print(dataTraining)
print()
print(dataTesting)

[[ 29   3  31  64   1   0  49   0  22   0   0   1   0]
 [  3   2  22  80   0   1  84   0  32   0   0   2   0]
 [  7   1  22  35   0   0  71   0  14   2   0   2   0]
 [ 22   1  14  67   0   1  76   0   8   2   0   2   0]
 [ 23   0  14 145   0   1  62   1   6   2   0   2   0]
 [ 23   0  28  25   0   1  47   0   4   1   0   1   0]
 [ 22   1  28 116   0   0  52   0  13   1   0   2   0]
 [ 10   1  14  92   0   1  72   0   0   2   0   3   0]
 [ 18   2  43  31   1   1  61   0   5   2   0   3   0]
 [ 23   2  34   9   0   1  73   0  16   2   0   2   0]
 [ 20   0  28  69   0   1  59   0  12   2   0   2   0]
 [ 14   2  22 103   0   1  38   0   2   2   0   2   0]
 [ 15   1  22  95   0   1  70   0   6   2   0   2   0]
 [ 30   3   8  42   0   0  43   1  17   1   0   2   0]
 [ 24   3  34 109   1   0  61   0  10   2   0   2   0]
 [ 16   2  14  50   0   1  57   0  16   1   0   2   0]
 [ 24   2  14 141   0   1  71   0   0   2   0   2   0]
 [ 32   3  34  57   0   1  15   0  25   0   0   2   0]
 [  9   0  34  77   0   1  70   0  15   2   0   2   0]
 [ 35   3  28  69   0   1  50   0  17   2   2   2   0]
 [ 17   2  22  85   0   0  48   0   5   2   0   2   0]
 [ 32   0  14 121   0   0  50   0   4   1   0   2   0]
 [ 28   2  22  62   0   1  45   0  17   1   3   3   0]
 [ 10   2   7   2   0   1  74   0   6   1   0   2   0]
 [ 29   2  25  81   0   0  71   0   0   2   0   2   0]
 [ 18   1  24  33   0   1  57   0   8   2   1   2   0]
 [ 14   0  15  53   0   0  83   0   0   2   0   2   0]
 [ 11   0  11  89   0   0  82   0   0   2   0   2   0]
 [  1   3  13  18   0   0  73   0   0   2   0   2   0]
 [ 23   0  20 122   0   0  58   0   0   2   1   2   0]
 [ 37   2   8  94   1   0  30   0   0   2   1   2   0]
 [ 20   1   7 128   0   1  55   0   0   2   0   3   0]
 [ 18   3  13  22   0   0  86   0   0   1   0   1   0]
 [  7   1  25  34   0   1  32   0   0   1   0   1   0]
 [ 24   2  28  42   1   0  64   0   0   2   0   2   0]
 [  2   0  27  19   0   1  80   0  14   2   0   2   0]
 [ 17   2   1  53   0   1  42   1  12   1   0   2   0]
 [ 11   1  22  65   0   0  74   0   6   1   0   2   0]
 [ 10   1  14  51   0   1  69   0   0   2   0   2   0]
 [ 28   0  17  40   0   1  62   0   0   2   0   2   0]]

[[ 25   0  25  65   0   1  60   0   5   1   0   3   0]
 [ 10   2  22  64   0   1  77   1   4   2   0   2   0]
 [  8   0  28  57   0   1  76   0   0   2   0   2   0]
 [ 27   2  34  73   1   1  36   1  10   1   0   2   0]
 [  6   3  28  31   0   1  76   1  14   2   0   3   0]
 [ 37   1  39 121   0   1  61   0   4   2   2   2   0]
 [ 25   2  34  43   1   1  56   0  16   2   0   2   0]
 [ 17   2   8  13   0   1  23   0   6   2   0   2   0]
 [ 31   2  28 150   1   0  56   0   8   2   1   2   0]
 [ 19   2  22  29   1   0  51   0  12   0   0   2   0]
 [  7   1   5  30   0   1  67   0   0   2   1   2   0]
 [ 31   0  14  15   0   1  39   0   4   2   0   3   0]
 [ 10   1  22  50   0   0  85   0   0   2   0   2   0]
 [ 20   2  18 101   0   0  51   0   5   0   1   2   0]
 [ 17   3  18  44   0   0  25   1  14   2   1   2   0]
 [ 12   2  29  15   0   0  59   1  14   0   0   2   0]
 [ 20   2  25 123   1   1  69   0   0   2   0   2   0]
 [ 20   2  34  63   0   0  64   0  16   2   0   3   0]
 [ 31   2  37  98   0   1  47   0   8   2   0   2   0]
 [ 31   2  39 146   0   0  50   0   8   2   0   2   0]
 [ 17   2  28 127   0   0  41   0  15   2   1   2   0]
 [ 14   1  22  75   0   0  78   0   2   1   0   2   0]
 [ 11   0   4  39   0   0  47   1  28   1   0   2   0]
 [ 19   0  22  93   0   0  42   0   4   1   0   2   0]
 [  5   2  28 134   0   0  80   0   0   2   0   2   0]
 [ 18   1  14 136   0   1  71   0   2   2   0   2   0]
 [ 10   2  28  66   0   0  78   0   0   2   0   2   0]
 [ 13   2  27  86   0   0  55   0   0   2   0   2   0]
 [ 19   2  20  47   0   0  16   0   0   2   0   0   0]
 [ 19   0  27  65   0   0  59   0   0   2   0   2   0]
 [ 20   2  14  87   0   0  46   0   4   1   0   3   0]
 [ 17   2   0  58   0   1  53   1   0   2   1   3   0]
 [  0   1  22  35   0   0  90   0   0   2   0   2   0]
 [ 17   0  28  90   0   0  83   1   0   2   0   2   0]
 [  9   2  15  44   0   1  64   0   2   1   0   2   0]
 [ 21   1  25  80   0   0  60   0  14   1   0   2   0]
 [ 17   2  18  75   1   0  65   0  23   1   0   2   0]
 [ 25   1  28  52   0   1  63   1   0   2   0   2   0]
 [ 18   1  20  36   1   1  81   0   0   2   0   2   0]
 [ 24   2   5  70   0   0  53   1   6   1   0   3   0]
 [  7   2   9  80   0   1  77   0   0   2   0   2   0]
 [ 11   1  20 127   0   0  69   0   0   2   0   2   0]
 [ 26   2   3 132   0   1  59   0   0   2   1   2   0]
 [ 18   3  35 118   1   1  76   0  12   1   0   3   0]
 [  8   0   3  94   0   0  22   0   6   1   0   2   0]
 [ 33   2  11 151   0   0  59   0  16   1   0   3   0]
 [ 34   2  13 105   0   1  50   0  10   2   1   3   0]
 [ 12   1   2  29   1   1  55   0   0   2   0   3   0]
 [ 20   2   8  45   0   1  57   0  16   1   0   2   0]
 [ 24   0   1  78   0   0  22   0  10   1   0   2   0]
 [ 14   2  17  84   1   1  74   0   0   2   2   2   0]
 [ 23   0  23  38   0   1  67   1   0   2   0   3   0]
 [ 18   2  27  54   0   1  68   0   0   2   4   2   0]
 [ 20   1  23 112   1   0  58   1   0   2   1   2   0]
 [ 11   1   9   5   0   1  37   0   0   1   0   2   0]
 [ 19   0  29  57   0   0  12   1   0   2   0   3   0]
 [ 28   0  28 147   0   0  56   0  12   1   0   2   0]
 [ 18   0   7  64   1   1  46   0   1   2   3   3   0]
 [  9   2  22 131   0   1  61   0  18   2   1   2   0]
 [ 19   2  22  76   1   0  72   0   0   2   3   2   0]]

In [27]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTraining)
print()
len(labelTraining)

[1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0
 0 0 0]

40

In [28]:
model = GaussianNB()

In [29]:
model = model.fit(inputTraining, labelTraining)

In [30]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya :", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya : [0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 1]
Hasil Prediksi : [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [31]:
#prediksi 40 & 60
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi benar :", prediksiBenar, "data")
print("Prediksi salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi benar : 47 data
Prediksi salah : 13 data
Akurasi : 78.33333333333333 %

In [32]:
#data 60 & 40
dataTraining = np.concatenate((irisDataset[0:30, :], irisDataset[50:80, :]), axis=0)
dataTesting = np.concatenate((irisDataset[30:50, :], irisDataset[80:100, :]), axis=0)
print(dataTraining)
print()
print(dataTesting)

[[ 29   3  31  64   1   0  49   0  22   0   0   1   0]
 [  3   2  22  80   0   1  84   0  32   0   0   2   0]
 [  7   1  22  35   0   0  71   0  14   2   0   2   0]
 [ 22   1  14  67   0   1  76   0   8   2   0   2   0]
 [ 23   0  14 145   0   1  62   1   6   2   0   2   0]
 [ 23   0  28  25   0   1  47   0   4   1   0   1   0]
 [ 22   1  28 116   0   0  52   0  13   1   0   2   0]
 [ 10   1  14  92   0   1  72   0   0   2   0   3   0]
 [ 18   2  43  31   1   1  61   0   5   2   0   3   0]
 [ 23   2  34   9   0   1  73   0  16   2   0   2   0]
 [ 20   0  28  69   0   1  59   0  12   2   0   2   0]
 [ 14   2  22 103   0   1  38   0   2   2   0   2   0]
 [ 15   1  22  95   0   1  70   0   6   2   0   2   0]
 [ 30   3   8  42   0   0  43   1  17   1   0   2   0]
 [ 24   3  34 109   1   0  61   0  10   2   0   2   0]
 [ 16   2  14  50   0   1  57   0  16   1   0   2   0]
 [ 24   2  14 141   0   1  71   0   0   2   0   2   0]
 [ 32   3  34  57   0   1  15   0  25   0   0   2   0]
 [  9   0  34  77   0   1  70   0  15   2   0   2   0]
 [ 35   3  28  69   0   1  50   0  17   2   2   2   0]
 [ 25   0  25  65   0   1  60   0   5   1   0   3   0]
 [ 10   2  22  64   0   1  77   1   4   2   0   2   0]
 [  8   0  28  57   0   1  76   0   0   2   0   2   0]
 [ 27   2  34  73   1   1  36   1  10   1   0   2   0]
 [  6   3  28  31   0   1  76   1  14   2   0   3   0]
 [ 37   1  39 121   0   1  61   0   4   2   2   2   0]
 [ 25   2  34  43   1   1  56   0  16   2   0   2   0]
 [ 17   2   8  13   0   1  23   0   6   2   0   2   0]
 [ 31   2  28 150   1   0  56   0   8   2   1   2   0]
 [ 19   2  22  29   1   0  51   0  12   0   0   2   0]
 [ 17   2  22  85   0   0  48   0   5   2   0   2   0]
 [ 32   0  14 121   0   0  50   0   4   1   0   2   0]
 [ 28   2  22  62   0   1  45   0  17   1   3   3   0]
 [ 10   2   7   2   0   1  74   0   6   1   0   2   0]
 [ 29   2  25  81   0   0  71   0   0   2   0   2   0]
 [ 18   1  24  33   0   1  57   0   8   2   1   2   0]
 [ 14   0  15  53   0   0  83   0   0   2   0   2   0]
 [ 11   0  11  89   0   0  82   0   0   2   0   2   0]
 [  1   3  13  18   0   0  73   0   0   2   0   2   0]
 [ 23   0  20 122   0   0  58   0   0   2   1   2   0]
 [ 37   2   8  94   1   0  30   0   0   2   1   2   0]
 [ 20   1   7 128   0   1  55   0   0   2   0   3   0]
 [ 18   3  13  22   0   0  86   0   0   1   0   1   0]
 [  7   1  25  34   0   1  32   0   0   1   0   1   0]
 [ 24   2  28  42   1   0  64   0   0   2   0   2   0]
 [  2   0  27  19   0   1  80   0  14   2   0   2   0]
 [ 17   2   1  53   0   1  42   1  12   1   0   2   0]
 [ 11   1  22  65   0   0  74   0   6   1   0   2   0]
 [ 10   1  14  51   0   1  69   0   0   2   0   2   0]
 [ 28   0  17  40   0   1  62   0   0   2   0   2   0]
 [ 20   2  14  87   0   0  46   0   4   1   0   3   0]
 [ 17   2   0  58   0   1  53   1   0   2   1   3   0]
 [  0   1  22  35   0   0  90   0   0   2   0   2   0]
 [ 17   0  28  90   0   0  83   1   0   2   0   2   0]
 [  9   2  15  44   0   1  64   0   2   1   0   2   0]
 [ 21   1  25  80   0   0  60   0  14   1   0   2   0]
 [ 17   2  18  75   1   0  65   0  23   1   0   2   0]
 [ 25   1  28  52   0   1  63   1   0   2   0   2   0]
 [ 18   1  20  36   1   1  81   0   0   2   0   2   0]
 [ 24   2   5  70   0   0  53   1   6   1   0   3   0]]

[[  7   1   5  30   0   1  67   0   0   2   1   2   0]
 [ 31   0  14  15   0   1  39   0   4   2   0   3   0]
 [ 10   1  22  50   0   0  85   0   0   2   0   2   0]
 [ 20   2  18 101   0   0  51   0   5   0   1   2   0]
 [ 17   3  18  44   0   0  25   1  14   2   1   2   0]
 [ 12   2  29  15   0   0  59   1  14   0   0   2   0]
 [ 20   2  25 123   1   1  69   0   0   2   0   2   0]
 [ 20   2  34  63   0   0  64   0  16   2   0   3   0]
 [ 31   2  37  98   0   1  47   0   8   2   0   2   0]
 [ 31   2  39 146   0   0  50   0   8   2   0   2   0]
 [ 17   2  28 127   0   0  41   0  15   2   1   2   0]
 [ 14   1  22  75   0   0  78   0   2   1   0   2   0]
 [ 11   0   4  39   0   0  47   1  28   1   0   2   0]
 [ 19   0  22  93   0   0  42   0   4   1   0   2   0]
 [  5   2  28 134   0   0  80   0   0   2   0   2   0]
 [ 18   1  14 136   0   1  71   0   2   2   0   2   0]
 [ 10   2  28  66   0   0  78   0   0   2   0   2   0]
 [ 13   2  27  86   0   0  55   0   0   2   0   2   0]
 [ 19   2  20  47   0   0  16   0   0   2   0   0   0]
 [ 19   0  27  65   0   0  59   0   0   2   0   2   0]
 [  7   2   9  80   0   1  77   0   0   2   0   2   0]
 [ 11   1  20 127   0   0  69   0   0   2   0   2   0]
 [ 26   2   3 132   0   1  59   0   0   2   1   2   0]
 [ 18   3  35 118   1   1  76   0  12   1   0   3   0]
 [  8   0   3  94   0   0  22   0   6   1   0   2   0]
 [ 33   2  11 151   0   0  59   0  16   1   0   3   0]
 [ 34   2  13 105   0   1  50   0  10   2   1   3   0]
 [ 12   1   2  29   1   1  55   0   0   2   0   3   0]
 [ 20   2   8  45   0   1  57   0  16   1   0   2   0]
 [ 24   0   1  78   0   0  22   0  10   1   0   2   0]
 [ 14   2  17  84   1   1  74   0   0   2   2   2   0]
 [ 23   0  23  38   0   1  67   1   0   2   0   3   0]
 [ 18   2  27  54   0   1  68   0   0   2   4   2   0]
 [ 20   1  23 112   1   0  58   1   0   2   1   2   0]
 [ 11   1   9   5   0   1  37   0   0   1   0   2   0]
 [ 19   0  29  57   0   0  12   1   0   2   0   3   0]
 [ 28   0  28 147   0   0  56   0  12   1   0   2   0]
 [ 18   0   7  64   1   1  46   0   1   2   3   3   0]
 [  9   2  22 131   0   1  61   0  18   2   1   2   0]
 [ 19   2  22  76   1   0  72   0   0   2   3   2   0]]

In [33]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTraining)
print()
len(labelTraining)

[1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]

60

In [34]:
model = GaussianNB()

In [35]:
model = model.fit(inputTraining, labelTraining)

In [36]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya :", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya : [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0
 1 0 1]
Hasil Prediksi : [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]

In [37]:
#prediksi 60 & 40
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi benar :", prediksiBenar, "data")
print("Prediksi salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi benar : 31 data
Prediksi salah : 9 data
Akurasi : 77.5 %